{% set name = "boost-headers" %}
{% set version = "1.34" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: boost_1_34_0.tar.gz
  url: http://www.cca-forum.org/download/cca-tools/dependencies/boost_1_34_0.tar.gz

build:
  number: 0
